# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/deliveroo-editions',
                'doc_host': 'https://ribenamaplesyrup.github.io',
                'git_url': 'https://github.com/ribenamaplesyrup/deliveroo-editions',
                'lib_path': 'deliveroo_editions'},
  'syms': {'deliveroo_editions.core': {'deliveroo_editions.core.foo': ('core.html#foo', 'deliveroo_editions/core.py')}}}
